name: "desi_w0wafid"
fiducial:
  Omegam: 0.3191
  Omegab: 0.049795
  h: 0.6674
  ns: 0.96605
  sigma8: 0.81
  w0: -0.752
  wa: -0.86
  mnu: 0.06
  Neff: 3.044
observables: ["GCph", "WL"]
options:
  accuracy: 1
  feedback: 1
  code: "class"
  survey_name: "Euclid"
  survey_name_photo: "Euclid-Photometric-ISTF-Pessimistic"
  survey_name_spectro: false
  specs_dir: "cosmicfishpie/configs/default_survey_specifications/"
  cosmo_model: "w0waCDM"
  class_config_yaml: "cosmicfishpie/configs/default_boltzmann_yaml_files/class/fast_photo.yaml"
priors:
  Omegam: [0.24, 0.4]
  Omegab:
    type: gaussian
    loc: 0.049795
    scale: 0.00055
  h: [0.61, 0.85]
  ns: [0.92, 1.00]
  sigma8: [0.79, 0.83]
  AIA: [1.0, 3.0]
  etaIA: [-6.0, 6.0]
  b1: [1.0, 3.0]
  b2: [1.0, 3.0]
  b3: [1.0, 3.0]
  b4: [1.0, 3.0]
  b5: [1.0, 3.0]
  b6: [1.0, 3.0]
  b7: [1.0, 3.0]
  b8: [1.0, 3.0]
  b9: [1.0, 3.0]
  b10: [1.0, 3.0]
sampler_settings:
  n_live: 1000
  n_networks: 64
  n_batch: 256
  pool: 8